---
apiVersion: v1
kind: Namespace
metadata:
  name: pihole
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 10m
  url: https://mojo2600.github.io/pihole-kubernetes/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 10m
  chart:
    spec:
      chart: pihole
      version: '2.31.0'
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: pihole
      interval: 10m
  values:
    image:
      tag: "2025.08.0"
    serviceDns:
        mixedService: true
        type: LoadBalancer
    serviceDhcp:
        enabled: false
    virtualHost: pihole.homecluster.lan
    ingress:
        enabled: true
        hosts:
          - pihole.homecluster.lan
    admin:
      existingSecret: admin # To be added manually after initial bootstrapping
    doh:
      enabled: false
    persistentVolumeClaim:
      enabled: true
      storageClass: longhorn
      size: "4Gi"
    DNS1: 9.9.9.9
    DNS2: 149.112.112.112
    dnsmasq:
      customDnsEntries:
        - address=/hos.lan/192.168.1.31
        - address=/homecluster.lan/192.168.1.43
        - address=/homecluster.lan/192.168.1.44
        - address=/homecluster.lan/192.168.1.45
        - address=/homecluster.lan/192.168.1.46
        - address=/homecluster.lan/192.168.1.47
      customSettings:
        - except-interface=nonexisting
    