---
apiVersion: v1
kind: Namespace
metadata:
  name: pihole
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 1m
  url: https://mojo2600.github.io/pihole-kubernetes/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 10m
  chart:
    spec:
      chart: pihole
      version: '2.26.2'
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: pihole
      interval: 10m
  values:
    serviceDns:
        mixedService: true
        type: LoadBalancer
    serviceDhcp:
        enabled: false
    virtualHost: rancher.local
    ingress:
        enabled: true
        hosts:
          - rancher.local
    admin:
      existingSecret: admin # To be added manually after initial bootstrapping
    doh:
      enabled: true
    DNS1: 1.1.1.1
    DNS2: 1.0.0.1
    dnsmasq:
      customDneEntries:
        - address=/homecluster.lan/192.168.1.43
        - address=/homecluster.lan/192.168.1.44
        - address=/homecluster.lan/192.168.1.45
        - address=/homecluster.lan/192.168.1.46
        - address=/homecluster.lan/192.168.1.47
      customCnameEntries:
        - cname=pi.hole,homecluster.lan
    