---
apiVersion: v1
kind: Namespace
metadata:
  name: pihole
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 1m
  url: https://mojo2600.github.io/pihole-kubernetes/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 10m
  chart:
    spec:
      chart: pihole
      version: '2.29.1'
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: pihole
      interval: 10m
  values:
    image:
      tag: "2025.04.0"
    adlists:
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.txt
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    serviceDns:
        mixedService: true
        type: LoadBalancer
    serviceDhcp:
        enabled: false
    virtualHost: pihole.homecluster.lan
    ingress:
        enabled: true
        hosts:
          - pihole.homecluster.lan
    admin:
      existingSecret: admin # To be added manually after initial bootstrapping
    doh:
      enabled: true
    persistentVolumeClaim:
      enabled: true
    DNS1: 1.1.1.1
    DNS2: 1.0.0.1
    dnsmasq:
      customDnsEntries:
        - address=/hos.lan/192.168.1.31
        - address=/homecluster.lan/192.168.1.43
        - address=/homecluster.lan/192.168.1.44
        - address=/homecluster.lan/192.168.1.45
        - address=/homecluster.lan/192.168.1.46
        - address=/homecluster.lan/192.168.1.47
      customSettings:
        - except-interface=nonexisting
    