---
apiVersion: v1
kind: Namespace
metadata:
  name: private-search
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: private-search
  namespace: private-search
spec:
  interval: 1m
  url: oci://ghcr.io/codayblue/private-search
  ref:
    tag: 0.1.4
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: private-search
  namespace: private-search
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: private-search
    namespace: private-search
  values:
    ingress:
      enabled: true
      hosts:
        - host: search.homecluster.lan
          paths:
            - path: /
              pathType: ImplementationSpecific
    