---
apiVersion: v1
kind: Namespace
metadata:
  name: snail-code-hunter
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sch
  namespace: flux-system
spec:
  interval: 1m0s
  secretRef:
    name: flux-system
  ref:
    branch: main
  url: ssh://git@github.com/codayblue/snail-code-hunter
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snail-code-hunter
  namespace: snail-code-hunter
spec:
  chart:
    spec:
      chart: ./chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: sch
        namespace: flux-system
  interval: 10m0s
